---
description: "Saiba mais sobre: ' GoTo <labelname> ' não é válido porque ' <labelname> ' está dentro de uma instrução ' Try ', ' Catch ' ou ' Finally ' que não contém esta instrução"
title: "'GoTo <labelname>' não é válido porque '<labelname>' está contido em uma instrução 'Try', 'Catch' ou 'Finally' que não contém essa instrução"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 952612fbac2304f57cf2d0a7ac6e701f1d5bb054
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100437404"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>'GoTo \<labelname>' não é válido porque '\<labelname>' está contido em uma instrução 'Try', 'Catch' ou 'Finally' que não contém essa instrução

Não é possível ramificar em um `Try...Catch...Finally` bloco.  
  
 **ID do erro:** BC30754  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Reestruture seu código para que o rótulo preceda o `Try...Catch...Finally` bloco.  
  
## <a name="see-also"></a>Consulte também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
