---
title: "'Exit Try' só pode aparecer dentro da instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 05df59cb710c83eada1eba4b7ddb1323fa0dd217
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91082175"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' só pode aparecer dentro da instrução 'Try'

`Exit Try` Só pode aparecer dentro de uma `Try` instrução Block. Você tem uma instrução redundante `Exit Try` ou sua `Exit Try` instrução aparece fora dos limites de seu `Try` bloco correspondente.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Localize e remova a instrução desnecessária `Exit Try` .  
  
2. Mova a `Exit Try` instrução para o local apropriado dentro do seu código.  
  
## <a name="see-also"></a>Confira também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
